from __future__ import annotations

from typing import Protocol

from backend.app.core.config import Settings
from backend.app.services.mongo_session_store import MongoSessionStore


class SessionStoreProtocol(Protocol):
    def create_user(self, full_name: str, email: str, password: str, state: str | None = None) -> dict: ...
    def get_user_by_email(self, email: str) -> dict | None: ...
    def get_user_by_google_sub(self, google_sub: str) -> dict | None: ...
    def authenticate_user(self, email: str, password: str) -> dict | None: ...
    def create_google_user(self, full_name: str, email: str, google_sub: str, state: str | None = None) -> dict: ...
    def link_google_account(self, user_id: int, google_sub: str) -> dict | None: ...
    def promote_user_to_admin(self, email: str) -> dict | None: ...
    def get_admin_stats(self) -> dict: ...
    def get_admin_analytics_overview(self, *, period: str = "24h", average_response_time_ms: float | None = None) -> dict: ...
    def get_admin_analytics_trends(self, *, period: str = "7d") -> dict: ...
    def get_admin_query_categories(self, *, period: str = "24h") -> dict: ...
    def get_admin_fallback_reasons(self, *, period: str = "24h") -> dict: ...
    def get_admin_quality_score(self, *, period: str = "24h") -> dict: ...
    def list_admin_low_quality_review_candidates(
        self,
        *,
        review_filter: str = "all",
        skip: int = 0,
        limit: int = 20,
    ) -> dict: ...
    def list_admin_users(self, *, search: str | None = None, skip: int = 0, limit: int = 20) -> dict: ...
    def list_admin_user_chats(self, user_id: int, *, skip: int = 0, limit: int = 20) -> dict | None: ...
    def get_admin_chat_messages(self, chat_id: int) -> dict | None: ...
    def list_admin_feedback(
        self,
        *,
        rating: str | None = None,
        recent_limit: int | None = None,
        skip: int = 0,
        limit: int = 20,
    ) -> dict: ...
    def record_admin_activity(
        self,
        *,
        admin_user: dict,
        action: str,
        target_type: str | None = None,
        target_id: int | str | None = None,
    ) -> dict: ...
    def list_admin_activity(self, *, skip: int = 0, limit: int = 20) -> dict: ...
    def get_runtime_config_bool(self, key: str) -> bool | None: ...
    def set_runtime_config_bool(self, *, key: str, value: bool, admin_user: dict) -> dict: ...
    def create_auth_session(self, user_id: int, duration_days: int = 14) -> str: ...
    def get_user_by_token(self, token: str) -> dict | None: ...
    def delete_auth_session(self, token: str) -> None: ...
    def create_password_reset_token(self, user_id: int, ttl_minutes: int = 30) -> str: ...
    def reset_password_with_token(self, token: str, new_password: str) -> dict | None: ...
    def create_session(self, title: str, user_id: int | None = None) -> dict: ...
    def get_session(self, chat_id: int, user_id: int | None = None) -> dict | None: ...
    def get_conversation_state(self, chat_id: int, user_id: int | None = None) -> dict: ...
    def update_conversation_state(self, chat_id: int, state: dict, user_id: int | None = None) -> dict: ...
    def add_message(
        self,
        chat_id: int,
        role: str,
        content: str,
        metadata: dict | None = None,
        user_id: int | None = None,
    ) -> dict: ...
    def add_message_feedback(
        self,
        *,
        message_id: int,
        user_id: int,
        rating: str,
        comment: str | None = None,
    ) -> dict | None: ...
    def list_sessions(self, user_id: int | None = None) -> list[dict]: ...
    def get_messages(self, chat_id: int, user_id: int | None = None) -> list[dict]: ...
    def clear_history(self, user_id: int | None = None) -> None: ...
    def delete_session(self, chat_id: int, user_id: int | None = None) -> bool: ...


def create_session_store(settings: Settings) -> SessionStoreProtocol:
    if settings.database_backend != "mongodb":
        raise RuntimeError("SQLite temporarily disabled during MongoDB migration")

    return MongoSessionStore(settings)
